version: "3.8"

services:
  client:
    container_name: opendesk_client
    image: opendesk-client:demo
    restart: always
    expose:
      - "80"

  api:
    container_name: opendesk_api
    image: opendesk-api
    expose:
      - "80"
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DB: "host=postgres;port=5432;database=opendesk;username=opendesk;password=opendesk"
      Application__IsDemo: true
      Application__SuperAdminEmail: ""
      Authentication__External__Microsoft__ClientId: ""
      Authentication__External__Microsoft__TenantId: ""
    depends_on:
      - postgres

  postgres:
    build:
      context: ./database
      dockerfile: ./Db.Dockerfile
    restart: always
    volumes:
      - opendesk_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "opendesk"
      POSTGRES_PASSWORD: "opendesk"
      POSTGRES_DB: "opendesk"
    # Log all queries
    # command: ["postgres", "-c", "log_statement=all"]

volumes:
  opendesk_postgres:
