version: "3.8"

services:
  client:
    container_name: opendesk_client
    image: opendesk-client:demo
    expose:
      - "80"

  api:
    container_name: opendesk_api
    image: opendesk-api
    expose:
      - "80"
    restart: always
    environment:
      ConnectionStrings__DB: "host=postgres;port=5432;database=opendesk;username=opendesk;password=opendesk"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres

  postgres:
    build:
      context: ./database
      dockerfile: ./Db.Dockerfile
    restart: always
    volumes:
      - opendesk_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "opendesk"
      POSTGRES_PASSWORD: "opendesk"
      POSTGRES_DB: "opendesk"
    # Log all queries
    # command: ["postgres", "-c", "log_statement=all"]

  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - "8080:8080"

volumes:
  opendesk_postgres:
