version: "3"

services:
    nginx:
      build:
        context: ./nginx
        dockerfile: Nginx.Dockerfile
      ports:
        - "80:80"
        - "443:443"
      restart: always

    opendesk-api:
      build: 
        context: ./opendesk-api
        dockerfile: ./src/OpenDesk.API/API.Dockerfile
      expose: 
        - "80"
      restart: always
      depends_on: 
        - nginx